### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by Gummibeer** [Astrotomic/astrotomic.info#1]
* [x] twitter card support
* [x] open graph meta tags
* [x] create more components
* [ ] thank you message in contributors section
